// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWpx7R7unffA1X4lsLqy7YsmTbJST5ClU',
    appId: '1:517392828037:web:7604f34e5f67d6eb1ccbec',
    messagingSenderId: '517392828037',
    projectId: 'glau-3785f',
    authDomain: 'glau-3785f.firebaseapp.com',
    storageBucket: 'glau-3785f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtwjJ0GxxHedpQ6vhJdKAsdbVCmV_8S9w',
    appId: '1:517392828037:android:2ef6098f180445ed1ccbec',
    messagingSenderId: '517392828037',
    projectId: 'glau-3785f',
    storageBucket: 'glau-3785f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-mjbJ3sYUMU_j1xFTbKzaUev8rwlJROw',
    appId: '1:517392828037:ios:dc73fa5d9bc7b6be1ccbec',
    messagingSenderId: '517392828037',
    projectId: 'glau-3785f',
    storageBucket: 'glau-3785f.appspot.com',
    iosClientId: '517392828037-ou08p6uk63emajaa4micaahd1nu2eaio.apps.googleusercontent.com',
    iosBundleId: 'com.example.glau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-mjbJ3sYUMU_j1xFTbKzaUev8rwlJROw',
    appId: '1:517392828037:ios:dc73fa5d9bc7b6be1ccbec',
    messagingSenderId: '517392828037',
    projectId: 'glau-3785f',
    storageBucket: 'glau-3785f.appspot.com',
    iosClientId: '517392828037-ou08p6uk63emajaa4micaahd1nu2eaio.apps.googleusercontent.com',
    iosBundleId: 'com.example.glau',
  );
}
